"use strict";

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const cssDir = path.join(root, ".next", "static", "css");
const publicCss = path.join(root, "public", "zenith.css");
const inlineModule = path.join(root, "src", "lib", "zenith-css-content.ts");

if (!fs.existsSync(cssDir)) {
  console.warn("[copy-css] no .next/static/css directory");
  process.exit(0);
}

const cssName = fs.readdirSync(cssDir).find((name) => name.endsWith(".css"));
if (!cssName) {
  console.warn("[copy-css] no css file found");
  process.exit(0);
}

const cssPath = path.join(cssDir, cssName);
const cssText = fs.readFileSync(cssPath, "utf8");

fs.copyFileSync(cssPath, publicCss);
fs.writeFileSync(
  inlineModule,
  `/* Auto-generated by scripts/copy-css.js — do not edit */\nexport const ZENITH_CSS = ${JSON.stringify(cssText)};\n`,
);

console.log(`[copy-css] wrote public/zenith.css and src/lib/zenith-css-content.ts from ${cssName}`);
